/**
 * The panel state machine, implemented.
 *
 * Types for it have lived in `state.ts` since the first commit; this is the
 * logic. It sits in core rather than in any view because `@quorum/web` and the
 * native iOS/Android UIs all drive the same states — that is how the flow
 * stays consistent across platforms without sharing rendering code
 * (`docs/adr/0008-native-mobile-ui-no-webview.md`).
 *
 * ```
 * idle → opening → composing → [picking] → capturing → submitting → done
 *                      ↑___________|            |
 *                                          queued (offline)
 * ```
 *
 * Four opinions are baked in. Each is a judgment call about what happens to a
 * user's typed words when something goes wrong, which is the only question
 * this file really answers.
 */

import type { ElementBlock, SubmissionKind } from './protocol.ts';
import type { OpenOptions } from './config.ts';
import type { PanelState, QuorumEventMap } from './state.ts';
import { Emitter, type EmitterOptions } from './emitter.ts';

export interface PanelContext {
  kind: SubmissionKind;
  /** What the user has typed. Survives `picking` and `error`. */
  draft: string;
  /** Per-submission context from `open({ context })`. */
  custom?: Record<string, unknown>;
  /** Set once the element picker resolves. */
  element?: ElementBlock;
  /** Client-generated ULID, known before the network round trip. */
  submissionId?: string;
  error?: Error;
  queueDepth?: number;
}

export type PanelEvent =
  | { type: 'open'; options?: OpenOptions }
  | { type: 'ready' }
  | { type: 'edit'; draft: string }
  | { type: 'setKind'; kind: SubmissionKind }
  | { type: 'pick' }
  | { type: 'picked'; element: ElementBlock }
  | { type: 'pickCancelled' }
  /** `id` is generated by the caller so it can be reported before sending. */
  | { type: 'submit'; id: string }
  | { type: 'captured' }
  | { type: 'captureFailed'; error: Error }
  | { type: 'accepted' }
  | { type: 'enqueued'; queueDepth: number }
  | { type: 'failed'; error: Error; recoverable?: boolean }
  | { type: 'retry' }
  | { type: 'close'; reason?: QuorumEventMap['close']['reason'] };

export interface PanelOptions extends EmitterOptions {
  /**
   * Whether a capture step runs between composing and submitting. When false
   * the machine goes straight to `submitting`, so a headless or capture-free
   * integration has no dead state to pass through.
   */
  capture?: boolean;
  /** Default kind when `open()` does not specify one. Default `feature_request`. */
  defaultKind?: SubmissionKind;
}

const INITIAL: PanelContext = { kind: 'feature_request', draft: '' };

export class PanelMachine {
  readonly #emitter: Emitter<QuorumEventMap>;
  readonly #capture: boolean;
  readonly #defaultKind: SubmissionKind;
  #state: PanelState = 'idle';
  #context: PanelContext;

  constructor(options: PanelOptions = {}) {
    const { capture, defaultKind, ...emitterOptions } = options;
    this.#emitter = new Emitter<QuorumEventMap>(emitterOptions);
    this.#capture = capture ?? true;
    this.#defaultKind = defaultKind ?? 'feature_request';
    this.#context = { ...INITIAL, kind: this.#defaultKind };
  }

  get state(): PanelState {
    return this.#state;
  }

  /** A copy — the caller cannot reach in and mutate the machine's context. */
  get context(): PanelContext {
    return { ...this.#context };
  }

  on: Emitter<QuorumEventMap>['on'] = (event, handler) => this.#emitter.on(event, handler);
  off: Emitter<QuorumEventMap>['off'] = (event, handler) => {
    this.#emitter.off(event, handler);
  };

  /**
   * **Opinion 1 — an illegal transition is ignored, never thrown.**
   *
   * This runs inside somebody else's production application. A double-clicked
   * send button firing `submit` twice, or a late `accepted` arriving after the
   * user closed the panel, is a routine race and must not throw into the host.
   * The return value reports whether the event applied, so a caller that cares
   * can check, and nothing crashes for one that does not.
   */
  send(event: PanelEvent): boolean {
    const from = this.#state;
    const next = this.#transition(event);
    if (next === undefined) return false;

    this.#state = next;
    if (next !== from) this.#emitter.emit('stateChange', { from, to: next });
    return true;
  }

  /**
   * Whether `submit` would be accepted right now — for disabling the button
   * without the view reimplementing the guard.
   *
   * Empty text is submittable when there is something else to say: an element
   * the picker resolved, or a rage report, which `docs/PROTOCOL.md` rule 4
   * explicitly calls valid and useful on its own.
   */
  get canSubmit(): boolean {
    if (this.#state !== 'composing') return false;
    return (
      this.#context.draft.trim() !== '' ||
      this.#context.element !== undefined ||
      this.#context.kind === 'rage'
    );
  }

  #transition(event: PanelEvent): PanelState | undefined {
    const state = this.#state;

    // Opinion 2 — close is always legal, from any state, and always lands on
    // idle. That is safe only because the queue persists an event before any
    // network attempt (`queue.ts`): by the time the machine is in `submitting`
    // the feedback is already durable, so abandoning the panel cannot lose it.
    // Without persist-before-send this transition would be a data-loss bug.
    if (event.type === 'close') {
      if (state === 'idle') return undefined;
      this.#emitter.emit('close', { reason: event.reason ?? 'user' });
      this.#context = { ...INITIAL, kind: this.#defaultKind };
      return 'idle';
    }

    // `open` is legal from any state the flow has finished in, not just idle.
    // A user who submits, reads the thanks, then clicks the nub again is
    // starting a new submission — requiring the host to close first would make
    // that a bug in every integration rather than a detail handled once here.
    if (event.type === 'open') {
      if (state !== 'idle' && state !== 'done' && state !== 'queued' && state !== 'error') {
        return undefined;
      }
      this.#context = {
        ...INITIAL,
        kind: event.options?.kind ?? this.#defaultKind,
        draft: event.options?.prefill ?? '',
        ...(event.options?.context !== undefined && { custom: event.options.context }),
      };
      this.#emitter.emit('open', { kind: this.#context.kind });
      return 'opening';
    }

    switch (state) {
      case 'idle':
        return undefined;

      case 'opening':
        if (event.type === 'ready') return 'composing';
        if (event.type === 'failed') return this.#fail(event.error, event.recoverable ?? false);
        return undefined;

      case 'composing':
        if (event.type === 'edit') {
          this.#context = { ...this.#context, draft: event.draft };
          return 'composing';
        }
        if (event.type === 'setKind') {
          this.#context = { ...this.#context, kind: event.kind };
          return 'composing';
        }
        // Opinion 3 — picking is a detour, not a restart. The panel collapses
        // so the user can click the broken element, and the draft they already
        // typed is still there when it comes back.
        if (event.type === 'pick') return 'picking';
        if (event.type === 'submit') {
          if (!this.canSubmit) return undefined;
          this.#context = { ...this.#context, submissionId: event.id };
          this.#emitter.emit('submit', { id: event.id });
          return this.#capture ? 'capturing' : 'submitting';
        }
        return undefined;

      case 'picking':
        if (event.type === 'picked') {
          this.#context = { ...this.#context, element: event.element };
          return 'composing';
        }
        if (event.type === 'pickCancelled') return 'composing';
        return undefined;

      // Opinion 4 — a failed capture is not a failed submission. PROTOCOL.md
      // decouples them deliberately: the envelope is what must land, and the
      // attachment is best-effort. Routing a capture error to `error` would
      // throw away a written submission to save a screenshot, which is
      // backwards.
      case 'capturing':
        if (event.type === 'captured' || event.type === 'captureFailed') return 'submitting';
        return undefined;

      case 'submitting':
        if (event.type === 'accepted') return 'done';
        if (event.type === 'enqueued') {
          this.#context = { ...this.#context, queueDepth: event.queueDepth };
          this.#emitter.emit('queued', {
            id: this.#context.submissionId ?? '',
            queueDepth: event.queueDepth,
          });
          return 'queued';
        }
        if (event.type === 'failed') return this.#fail(event.error, event.recoverable ?? true);
        return undefined;

      case 'error':
        // The draft is deliberately not cleared on the way in, so retry lands
        // the user back on their own words rather than an empty box. Losing a
        // paragraph of typed feedback to a network blip is the fastest way to
        // never get that feedback again.
        if (event.type === 'retry') {
          this.#context = { ...this.#context };
          delete this.#context.error;
          return 'composing';
        }
        return undefined;

      case 'done':
      case 'queued':
        return undefined;
    }
  }

  #fail(error: Error, recoverable: boolean): PanelState {
    this.#context = { ...this.#context, error };
    this.#emitter.emit('error', { error, recoverable });
    return 'error';
  }
}
